== API Specs

=== Focus of the Sprint

* OGC API - Coverages
** spec http://docs.opengeospatial.org/DRAFTS/19-087.html
** repository https://github.com/opengeospatial/ogc_api_coverages

=== Other related specs

* OGC API - Common
** repository https://github.com/opengeospatial/oapi_common

* OpenAPI
** spec https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md

=== Media types used for the Sprint

* CIS JSON

`application/json`


* CoverageJSON

`application/prs.coverage+json`


=== Link relation types


*{datasetAPI}/*

Introduce a ‘dataset’ LRT to identify the Landing Page of a dataset.

http://www.opengis.net/def/rel/ogc/1.0/dataset


*{datasetAPI}/api* (not a fixed path)

service-desc


*{datasetAPI}/api* (not a fixed path)

service-doc


*{datasetAPI}/conformance*

http://www.opengis.net/def/rel/ogc/1.0/conformance



*{datasetAPI}/collections*

http://www.opengis.net/def/rel/ogc/1.0/data


*{datasetAPI}/collections/{coverageId}*

The issue is that the semantics of the IANA collection link relation do not neatly fit how it has been used.

The link will be 'self'. A specific relation type should be defined. This issue will be refered to the OGC API - Common SWG for discussion. One option would be use geodata, another option would be to use an OGC collection (http://www.opengis.net/def/rel/ogc/1.0/collection) instead of an IANA one.

The links would be provided at `/collections`.

Everything except the domainset and rangetype will be included in the `/collections`. The `/collections` would also include a link to the full metadata as well as a link to the CIS.







